package com.amber.crandomizer.java;


import java.util.ArrayList;
import java.util.List;

public class ChampionListClass {

    private List<String> ChampionList;

    public ChampionListClass() {


        ChampionList = new ArrayList<>();

        ChampionList.add("Aatrox");
        ChampionList.add("Ahri");
        ChampionList.add("Akali");
        ChampionList.add("Alistar");
        ChampionList.add("Amumu");
        ChampionList.add("Anivia");
        ChampionList.add("Annie");
        ChampionList.add("Aphelios");
        ChampionList.add("Ashe");
        ChampionList.add("Aurelion Sol");
        ChampionList.add("Azir");
        ChampionList.add("Bardo");
        ChampionList.add("Blitzcrank");
        ChampionList.add("Brand");
        ChampionList.add("Braum");
        ChampionList.add("Caitlyn");
        ChampionList.add("Camille");
        ChampionList.add("Cassiopeia");
        ChampionList.add("Cho´Gath");
        ChampionList.add("Corki");
        ChampionList.add("Darius");
        ChampionList.add("Diana");
        ChampionList.add("Dr.Mundo");
        ChampionList.add("Draven");
        ChampionList.add("Ekko");
        ChampionList.add("Elise");
        ChampionList.add("Evelynn");
        ChampionList.add("Ezreal");
        ChampionList.add("Fiddlesticks");
        ChampionList.add("Fiora");
        ChampionList.add("Fizz");
        ChampionList.add("Galio");
        ChampionList.add("Gangplank");
        ChampionList.add("Garen");
        ChampionList.add("Gnar");
        ChampionList.add("Gragas");
        ChampionList.add("Graves");
        ChampionList.add("Hecarim");
        ChampionList.add("Heimerdinger");
        ChampionList.add("Illaoi");
        ChampionList.add("Irelia");
        ChampionList.add("Ivern");
        ChampionList.add("Janna");
        ChampionList.add("Jarvan IV");
        ChampionList.add("Jax");
        ChampionList.add("Jayce");
        ChampionList.add("Jhin");
        ChampionList.add("Jinx");
        ChampionList.add("Kai´Sa");
        ChampionList.add("Kalista");
        ChampionList.add("Karma");
        ChampionList.add("Karthus");
        ChampionList.add("Kassadin");
        ChampionList.add("Katarina");
        ChampionList.add("Kayle");
        ChampionList.add("Kayn");
        ChampionList.add("Kennen");
        ChampionList.add("Kha´Zix");
        ChampionList.add("Kindred");
        ChampionList.add("Kog´Maw");
        ChampionList.add("LeBlanc");
        ChampionList.add("Lee Sin");
        ChampionList.add("Leona");
        ChampionList.add("Lissandra");
        ChampionList.add("Lucian");
        ChampionList.add("Lulu");
        ChampionList.add("Lux");
        ChampionList.add("Malphite");
        ChampionList.add("Malzahar");
        ChampionList.add("Maokai");
        ChampionList.add("Master Yi");
        ChampionList.add("Miss Fortune");
        ChampionList.add("Mordekaiser");
        ChampionList.add("Morgana");
        ChampionList.add("Nami");
        ChampionList.add("Nasus");
        ChampionList.add("Nautilus");
        ChampionList.add("Neeko");
        ChampionList.add("Nidalee");
        ChampionList.add("Nocturne");
        ChampionList.add("Nunu and Willump");
        ChampionList.add("Olaf");
        ChampionList.add("Orianna");
        ChampionList.add("Ornn");
        ChampionList.add("Pantheon");
        ChampionList.add("Poppy");
        ChampionList.add("Pyke");
        ChampionList.add("Qiyana");
        ChampionList.add("Quinn");
        ChampionList.add("Rakan");
        ChampionList.add("Rammus");
        ChampionList.add("Rek´Sai");
        ChampionList.add("Renekton");
        ChampionList.add("Rengar");
        ChampionList.add("Riven");
        ChampionList.add("Rumble");
        ChampionList.add("Ryze");
        ChampionList.add("Sejuani");
        ChampionList.add("Senna");
        ChampionList.add("Sett");
        ChampionList.add("Shaco");
        ChampionList.add("Shen");
        ChampionList.add("Shyvana");
        ChampionList.add("Singed");
        ChampionList.add("Sion");
        ChampionList.add("Sivir");
        ChampionList.add("Skarner");
        ChampionList.add("Sona");
        ChampionList.add("Soraka");
        ChampionList.add("Swain");
        ChampionList.add("Sylas");
        ChampionList.add("Syndra");
        ChampionList.add("Tahm Kench");
        ChampionList.add("Taliyah");
        ChampionList.add("Talon");
        ChampionList.add("Taric");
        ChampionList.add("Teemo");
        ChampionList.add("Tresh");
        ChampionList.add("Tristana");
        ChampionList.add("Trundle");
        ChampionList.add("Tryndamere");
        ChampionList.add("Twisted Fate");
        ChampionList.add("Twitch");
        ChampionList.add("Udyr");
        ChampionList.add("Urgot");
        ChampionList.add("Varus");
        ChampionList.add("Vayne");
        ChampionList.add("Veigar");
        ChampionList.add("Vel´Koz");
        ChampionList.add("Vi");
        ChampionList.add("Viktor");
        ChampionList.add("Vladimir");
        ChampionList.add("Volibear");
        ChampionList.add("Warwick");
        ChampionList.add("Wukong");
        ChampionList.add("Xayah");
        ChampionList.add("Xerath");
        ChampionList.add("Xin Zhao");
        ChampionList.add("Yasuo");
        ChampionList.add("Yorick");
        ChampionList.add("Yuumi");
        ChampionList.add("Zac");
        ChampionList.add("Zed");
        ChampionList.add("Ziggs");
        ChampionList.add("Zilean");
        ChampionList.add("Zoe");
        ChampionList.add("Zyra");
    }
    public List<String> getList() {
        return ChampionList;
    }
}